LangString addOrReinstall ${LANG_POLISH} "Dodaj/Zainstaluj ponownie składniki"
LangString alreadyInstalled ${LANG_POLISH} "Już zainstalowano"
LangString alreadyInstalledLong ${LANG_POLISH} "${PRODUCTNAME} ${VERSION} jest już zainstalowany. Wybierz operację, którą chcesz wykonać, i kliknij Dalej, aby kontynuować."
LangString appRunning ${LANG_POLISH} "{{product_name}} jest uruchomiony! Najpierw go zamknij, a potem spróbuj ponownie."
LangString appRunningOkKill ${LANG_POLISH} "{{product_name}} jest uruchomiony!$\nKliknij OK, aby go zamknąć"
LangString chooseMaintenanceOption ${LANG_POLISH} "Wybierz operację konserwacji do wykonania."
LangString choowHowToInstall ${LANG_POLISH} "Wybierz sposób instalacji ${PRODUCTNAME}."
LangString createDesktop ${LANG_POLISH} "Utwórz skrót na pulpicie"
LangString dontUninstall ${LANG_POLISH} "Nie odinstalowuj"
LangString dontUninstallDowngrade ${LANG_POLISH} "Nie odinstalowuj (instalacja starszej wersji bez odinstalowania jest wyłączona dla tego instalatora)"
LangString failedToKillApp ${LANG_POLISH} "Nie udało się zamknąć {{product_name}}. Najpierw zamknij aplikację i spróbuj ponownie"
LangString installingWebview2 ${LANG_POLISH} "Instalowanie WebView2..."
LangString newerVersionInstalled ${LANG_POLISH} "Nowsza wersja ${PRODUCTNAME} jest już zainstalowana! Instalowanie starszej wersji nie jest zalecane. Jeśli naprawdę chcesz ją zainstalować, najlepiej najpierw odinstalować obecną wersję. Wybierz operację, którą chcesz wykonać, i kliknij Dalej, aby kontynuować."
LangString older ${LANG_POLISH} "starsza"
LangString olderOrUnknownVersionInstalled ${LANG_POLISH} "W systemie jest zainstalowana $R4 wersja ${PRODUCTNAME}. Zaleca się odinstalowanie obecnej wersji przed instalacją. Wybierz operację, którą chcesz wykonać, i kliknij Dalej, aby kontynuować."
LangString silentDowngrades ${LANG_POLISH} "Instalacja starszych wersji jest wyłączona dla tego instalatora, więc nie można kontynuować instalacji cichej. Użyj zamiast tego instalatora z interfejsem graficznym.$\n"
LangString unableToUninstall ${LANG_POLISH} "Nie można odinstalować!"
LangString uninstallApp ${LANG_POLISH} "Odinstaluj ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_POLISH} "Odinstaluj przed instalacją"
LangString unknown ${LANG_POLISH} "nieznana"
LangString webview2AbortError ${LANG_POLISH} "Nie udało się zainstalować WebView2! Aplikacja nie może działać bez niego. Spróbuj uruchomić instalator ponownie."
LangString webview2DownloadError ${LANG_POLISH} "Błąd: pobieranie WebView2 nie powiodło się - $0"
LangString webview2DownloadSuccess ${LANG_POLISH} "Instalator WebView2 został pobrany pomyślnie"
LangString webview2Downloading ${LANG_POLISH} "Pobieranie instalatora WebView2..."
LangString webview2InstallError ${LANG_POLISH} "Błąd: instalacja WebView2 zakończyła się niepowodzeniem z kodem wyjścia $1"
LangString webview2InstallSuccess ${LANG_POLISH} "WebView2 został zainstalowany pomyślnie"
LangString deleteAppData ${LANG_POLISH} "Usuń dane aplikacji"
